### ISSUE TITLE
[Bug] Lockers don't open when having keycard in inventory

### ISSUE THREAD

**Issue by Oyplap** [SrLicht/RemoteKeycard#1]
Steps to reproduce:

1. Install Plugin (v1.0.1)
2. Add any keycard into your inventory.
3. Try to open locker without holding keycard.
4. It doesn't open all of the time.
5. Try holding the keycard.
6. Locker opens

I attached screenshots on where else it happens. it might be more
![Screenshot 2022-12-30 162436](https://user-images.githubusercontent.com/45702131/210087456-1f9db815-ca28-4751-b74a-3adcee321487.png)
![Screenshot 2022-12-30 162338](https://user-images.githubusercontent.com/45702131/210087462-212cae76-3dfa-4d19-b4ab-5ee70e7ee3b7.png)
![Screenshot 2022-12-30 162757](https://user-images.githubusercontent.com/45702131/210087451-719d27bf-205d-4e2b-aca8-4578237d956c.png)

**Comment by SrLicht** [comment]
The plugin is supposed to ignore those lockers, since I only want it to work with the LockerChamber (SCPs Chamber). Thanks for reporting for now put IsEnabled = false

**Comment by SrLicht** [comment]
This new version should solve this problem https://github.com/SrLicht/RemoteKeycard/releases/tag/1.0.2
