### ISSUE TITLE
[Bug] Access denied 

### ISSUE THREAD

**Issue by Oyplap** [SrLicht/RemoteKeycard#2]
When having a keycard and opening doors, everything works perfectly, but everytime you open a locked door, it gives that red access denied sound. But it still opens that locked door. I'm not sure if it is intended.

**Comment by SrLicht** [comment]
I did some research and it is because the PlayerInteractLocker event happens after the permissions are checked so it will give an error but the plugin then executes and will open the door/locker chamber.

**Comment by SrLicht** [comment]
It's not a bug, it's a Skill Issue of mine or of the game 💀

**Comment by SrLicht** [comment]
I can confirm that it is a Skill issue of mine, since I can cancel the event, in one hour I will have a fix.

**Comment by SrLicht** [comment]
https://github.com/SrLicht/RemoteKeycard/releases/tag/1.1.0 :)
