### ISSUE TITLE
Plugin fails to take effect

### ISSUE THREAD

**Issue by SHTLUOLEI** [SrLicht/RemoteKeycard#6]
No error was reported at runtime, but when I put the card away, I couldn't open any doors
My configuration looks like this
![Screenshot 2023-01-13 013327](https://user-images.githubusercontent.com/112939682/212146465-2e978553-9ba6-4e35-b3cc-3aa0924b406c.png)

Then, after I opened traditonal_methods, I found that I could only open SCP locker, while other doors with permission, such as 914,330, still could not be opened

Since there was no error in inserting, I also opened debug, and there was no problem, so I don't know what caused it

I am running the server on my own computer with windows 11

![Screenshot 2023-01-13 021928](https://user-images.githubusercontent.com/112939682/212147323-20d03f1a-df52-440a-8a9d-a8044c33c3ff.png)

**Comment by SrLicht** [comment]
Could you activate the Log.Debug and send me a screenshot of the console ?

**Comment by SrLicht** [comment]
https://github.com/SrLicht/RemoteKeycard/releases/tag/1.1.5
In any case try this version using traditional methods on true
